### ISSUE TITLE
Problemas con Markdown

### ISSUE THREAD

**Issue by FabianGil** [compbios/qui-n-soy-grchiquillo#1]
Hola @grchiquillo 

Te invito a revisar las guías del lenguaje Markdown, la versión subida del perfil no emplea de forma correcta los códigos, por eso no cambia la apariencia. Por ejemplo, se debe dejra un espacio entre el simbolo numneral y el texto; tampoco se debe dejar espacio en los asteriscos y el texto

# Te invito a revisar y mejorar tu perfil

La **práctica** hace que cada vez logres **mejores** *resultados* :trophy:

**Comment by grchiquillo** [comment]
Hice el ajuste de acuerdo a su comentario.
